# Generated by Django 4.2.17 on 2025-04-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tg', '0002_alter_tguser_options_remove_tguser_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WATER', 'Water'), ('SPORT', 'Sport'), ('CHALLENGE', 'Challenge'), ('MOTIVATION', 'Motivation'), ('ALL', 'All'), ('EVENT', 'Event')], max_length=64)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Напоминалка',
                'verbose_name_plural': 'Напоминалки',
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('periodicity', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('custom', 'Произвольное расписание'), ('no', 'Не оповещать')], default='no', max_length=10, verbose_name='Периодичность')),
                ('time', models.TimeField(verbose_name='Время отправки')),
                ('week_days', models.CharField(blank=True, help_text='1-Понедельник, 2-Вторник,..., 7-Воскресенье', max_length=20, null=True, verbose_name='Дни недели (через запятую)')),
                ('cron_minute', models.CharField(default='*', max_length=50, verbose_name='Минуты')),
                ('cron_hour', models.CharField(default='*', max_length=50, verbose_name='Часы')),
                ('cron_day_of_week', models.CharField(default='*', max_length=50, verbose_name='Дни недели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Расписание оповещений',
                'verbose_name_plural': 'Расписания оповещений',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WATER', 'Water'), ('SPORT', 'Sport'), ('CHALLENGE', 'Challenge'), ('MOTIVATION', 'Motivation'), ('ALL', 'All'), ('EVENT', 'Event')], max_length=64, verbose_name='Тип уведомления')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app_notification.notificationschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app_tg.tguser')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
