# Generated by Django 4.2.17 on 2025-05-01 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notification.notification', verbose_name='Последнее уведомление'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_notify',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата последнего уведомления'),
        ),
    ]
