# Generated by Django 4.2.17 on 2025-05-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0002_subscription_last_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'verbose_name': 'Тип напоминалки', 'verbose_name_plural': 'Типы напоминалок'},
        ),
    ]
