# Generated by Django 4.2.17 on 2025-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0003_alter_notificationtype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtype',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_user_type'),
        ),
    ]
