version: '3.7'

services:
  web: # &sportik
    container_name: sport_bot
    build: ./src
    restart: always
    volumes:
      - ./src:/usr/src/
    ports:
      - "8000:80"
    env_file:
      - ./src/.env
    depends_on:
      db:
        condition: service_healthy
    logging:
      options:
        max-size: 50m
    networks:
      - bot_bridge

  db:
    container_name: postgres_bot
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    env_file:
      - ./src/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: 50m
    networks:
       - bot_bridge

#  redis:
#    container_name: redis_bot
#    image: redis/redis-stack-server:latest
#    environment:
#      - REDIS_ARGS=--save 1200 32
#    volumes:
#      - ./redis/data:/data
#    ports:
#      - "6399:6379"
#    restart: unless-stopped
#    logging:
#      options:
#        max-size: 50m
#    networks:
#      - bot_bridge
#
#  celery:
#    <<: *sportik
#    container_name: celery_bot
#    entrypoint: /bin/bash -c "celery -A web worker -l INFO"
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    ports: []
#    networks:
#      - bot_bridge

networks:
  bot_bridge:
    driver: bridge
