# Generated by Django 4.2.17 on 2025-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='user',
        ),
        migrations.AddField(
            model_name='tguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Тег в ТГ'),
        ),
    ]
