# Generated by Django 4.2.17 on 2025-04-19 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tg', '0002_alter_tguser_options_remove_tguser_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название соревнования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание соревнования')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Дата начала соревнования')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дата окончания соревнования')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('score', models.IntegerField(default=0, verbose_name='Счёт')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app_competition.competition', verbose_name='Соревнование')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app_tg.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Cчёт',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
